### ISSUE TITLE
GLSL version 130 is not supported on macOS

### ISSUE THREAD

**Issue by syoyo** [lighttransport/gltf-insight#21]
OpenGL context version: 4.1

```
unlit vertex shader build error: ERROR: 0:1: '' :  version '130' is not supported
```

https://stackoverflow.com/questions/20264814/glsl-version-130-on-mac-os-x-causes-error

**Comment by Ybalrid** [comment]
I remember reading about this... OpenGL support by MacOs is a bit lacking. We need to switch to core profile strictly, not a "compatible" OpenGL context.

This is doable by setting the right "window hints" to GLFW before creating window and context.

I already replaced the OpenGL2 backed for ImGui by the OpenGL3+ one. Now, there's a few "old style" OpenGL calls in the code that draw the skeleton that needs to be changed. Not a big deal, need to convert a glBegin that draws point/line to a glDrawX call with some data put on the GPU instead. 

I'll get back to you on that shortly.

**Comment by Ybalrid** [comment]
So, while looking at #22, and considering the OpenGL support on Mac, I think it would be reasonable to simply rely on having available a core OpenGL profile. Any reasonably modern Hardware would support OpenGL 3.3 and up anyway. If you are okay with that, it becomes a non issue. 

This makes the canonical version of GLSL to use `#version 330`, and should be compatible with pretty much anything OpenGL runs on today.

Most of the GL code is doing is actually fairly simple anyway. The future portage of that code towards OpenGL ES 3.0 for mobile platform should go pretty smoothly

**Comment by Ybalrid** [comment]
All shader are either interpreted as **GLSL 3.30** or **ESSL 3.0**, depending on platform.

I'm now closing this issue. If we have any troubles on macOS now it will not be due to the *version* of the sharers.
