### ISSUE TITLE
[feature] Display and edit skin weights

### ISSUE THREAD

**Issue by syoyo** [lighttransport/gltf-insight#26]
* [x] Display weight value
* [x] Edit skin weights in spread sheet UI
~~* [ ] Painting skin weights(using ray casting)~~ (Moved to #35 for 8/E)

**Comment by Ybalrid** [comment]
I'm going to concentrate on the "spreadsheet stkye UI". As you put painting with the mouse for end of august, I'm going to move that to it's own issue

**Comment by Ybalrid** [comment]
This commit implement all the checked points here f583ebe05fbec540d8088a497a103f2e78cb4563
