### ISSUE TITLE
[feature] Information picker

### ISSUE THREAD

**Issue by syoyo** [lighttransport/gltf-insight#29]
We want to inspect vertex position/uv/normal, material id, weights value, etc of loaded glTF model.

* [x] Pick bones/vertex/face using ray casting
* [x] Display information of selected bone/vertex/face(position, normal, uv, material/texture, etc)

**Comment by Ybalrid** [comment]
infrastructure for ray cast picking works on my hand to find the face already. Currently working on adding the vertex and bone picking, will push this soon.

**Comment by Ybalrid** [comment]
@syoyo Could you take a look at this : https://github.com/lighttransport/nanort/pull/47 ?

**Comment by Ybalrid** [comment]
![clicking (1)](https://user-images.githubusercontent.com/1816251/61572650-48d6bd00-aaa1-11e9-994d-3ff276ecf72a.gif)

@syoyo Take a look at the GIF above.

I still need to refine it a tiny bit, but here's the gist of what's going on

1. clicking on view-port check which known sub-mesh is under the cursor
1. if you haven't clicked on a void space, we found what part of the geometry was just under the cursor, we shoot a ray to find a triangle (we get mesh data, transform it to world space, construct NanoRT geometry, shot ray from camera through cursor)
1. from finding triangle, we calculate (squared) distance from each vertex to the hit point. We choose the vertex that was closest, and it's marked as the "active vertex"
1. each vertex on the intersected polygon is flagged as the "active polygon"
1. active polygon indices are sent to shader, shader knows when current fragment was from the clicked polygon, if so, it will be rendered in bright orange
1. active vertex is drawn over with a big bright orange point
1. If mesh has skinning, skinning weights is checked. Joint that has the highest weight on vertex is set as current "active joint". This permit to control it with 3D gizmo
1. A window is created when valid selection is present, it contains info about the selected geometry (still need to add better display to that, and uv/normals are missing in the animation above). If mesh skinned, all the skinning data (weight/joint arrays for vertex) are shown.

Current quirks are : 

1. As of now, this only works on "TRIANGLE_LIST" GLTF primitives. Code that interact with NanoRT has to take the TRIANGLE_{STRIP/FAN} case into account
1. Skinned mesh needs to have CPU-side vertex data available. Thus, selection of skinned mesh only works when "soft skinning" mode is turned on. Current soft-skinning implementation is slow, and currently, this mode is turned off by default. I'm probably going to make it "on" by default. CPU Skinning performance can be improved later easily (by threading it, and by not recomputing things if joint pose data did not change.)

**Comment by Ybalrid** [comment]
Cat you take a look to this ? 
https://github.com/lighttransport/nanort/pull/48
