### ISSUE TITLE
Please upload AppImage to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [lighttransport/gltf-insight#4]
https://github.com/lighttransport/gltf-insight/blob/2bbf56f2294c36d72cecc93dea3b36ef36ba355a/.travis.yml#L71

Please upload AppImage to GitHub Releases, thank you. Maybe https://github.com/probonopd/uploadtool can help.

**Comment by Ybalrid** [comment]
I finished following the guide. I'm using upload.sh to push releases to GitHub. 

https://github.com/lighttransport/gltf-insight/releases/tag/continuous

I'm just learning how all of this works, and knew I was going to need to do that, but hey, thanks for the tip!
